// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52p9u6d5iThBAX8cRCY7VFrfkCi1ns4c',
    appId: '1:926319000467:android:04bcb2b0329b0141888666',
    messagingSenderId: '926319000467',
    projectId: 'local-app-30fb0',
    storageBucket: 'local-app-30fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB572kwZcDDfzGzRNLy27BN_UMSDYN8ZlQ',
    appId: '1:926319000467:ios:16fde60fab22aaef888666',
    messagingSenderId: '926319000467',
    projectId: 'local-app-30fb0',
    storageBucket: 'local-app-30fb0.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAElVtS2QFv8pYeapDQhFVbiaSoVfVZ98o',
    appId: '1:926319000467:web:9c61e5cb66ac1b59888666',
    messagingSenderId: '926319000467',
    projectId: 'local-app-30fb0',
    authDomain: 'local-app-30fb0.firebaseapp.com',
    storageBucket: 'local-app-30fb0.firebasestorage.app',
    measurementId: 'G-9Q7V325H3X',
  );

}